# Generated by Django 5.2.3 on 2025-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laptm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laptm_app',
            new_name='Member',
        ),
    ]
